version : "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app1:
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: avoy
      MONGO_INITDB_ROOT_PASSWORD: avoy123
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes: 
  mongo-db: