version : "3"
services : 
  nginx:
    ports:
      - "80:80"
  app1:
    image: avoy021/test-app1
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm run start 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
volumes: 
  mongo-db: