version : "3"
services : 
  nginx:
    ports:
      - "5000:80"
  app1:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev