version : "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app1:
    # env_file:
    #   - ./.env
    depends_on:
      - mongo
  redis:
    image: redis

